name: WindoomRPG
version: 0.1a
#prefix: wRPG
main: com.shaneschulte.plugins.windoomrpg.WindoomRPG
authors: [Hikeru, CoolGamrSms]
website: http://windoom.com/index.php
description: RPG core for Windoom SMP
depend: [WorldGuard, WorldEdit, SimpleClans, MCCore, SkillAPI, LWC, CreeperHeal, Vault, Citizens, EffectLib]
