name: WindoomRPG
version: 0.1a
#prefix: wRPG
main: com.shaneschulte.plugins.windoomrpg.WindoomRPG
authors: [Hikeru]
website: http://windoom.com/index.php
description: RPG core for Windoom SMP
depend: [Citizens, WorldGuard, SimpleClans, MCCore, SkillAPI, LWC, CreeperHeal, Vault]

